### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by zedrdave** [ryanwang520/flask_sqlalchemy-stubs#1]
Hi,

Are you working on this project? I think currently the repo only contains the default stubgen output?

I am considering trying my hand at a proper stubs file, but don't want to double the effort…

**Comment by ryanwang520** [comment]
The stubgen result is just enough for my usage, although it's easy to add class attributes like (`Column`, `Integer`, `relationship`) to `flask_sqlalchemy.SQLAlchemy` stubs. 

while you'd better just import from `sqlalchemy`  directly to better cope with [sqlalchemy stubs](https://github.com/dropbox/sqlalchemy-stubs) and its mypy plugin.
